Repository ReactiveX/rxdart, pull requests merged in 2021-09, with the labels that each got.

#617 fix(onErrorResume): still adds data when Stream emits an error
  lib/src/transformers/on_error_resume.dart
  test/transformers/on_error_resume_test.dart
  test/transformers/on_error_return_test.dart
  test/transformers/on_error_return_with_test.dart
Labels: bug

#614 `groupBy`: add duration selector
  CHANGELOG.md
  lib/src/transformers/group_by.dart
  test/transformers/group_by_test.dart
Labels: enhancement

#592 Add `delayWhen`
  CHANGELOG.md
  README.md
  lib/src/transformers/delay_when.dart
  lib/src/utils/forwarding_stream.dart
  lib/transformers.dart
  test/rxdart_test.dart
  test/transformers/delay_when_test.dart
  test/transformers/flat_map_test.dart
Labels: enhancement

#611 `ignoreElements`: remove `@deprecated`, change return type to `Stream<Never>`
  CHANGELOG.md
  lib/src/transformers/ignore_elements.dart
  lib/src/transformers/take_last.dart
  test/transformers/ignore_elements_test.dart
  test/transformers/take_last_test.dart
Labels: enhancement

#623 fix(flatMap): create inner Stream lazily
  lib/src/transformers/flat_map.dart
  test/transformers/flat_map_test.dart
Labels: bug, enhancement

#624 update(takeLast): simplify the implementation
  lib/src/transformers/take_last.dart
  test/transformers/take_last_test.dart
Labels: enhancement

#630 refactor(Connectable): introduce AbstractConnectableStream
  lib/src/streams/connectable_stream.dart
  test/streams/publish_connectable_stream_test.dart
  test/streams/replay_connectable_stream_test.dart
  test/streams/value_connectable_stream_test.dart
  test/transformers/timeout_test.dart
  test/transformers/where_type_test.dart
Labels: enhancement

#631 refactor(BehaviorSubject, ReplaySubject): internally using Sentinel object instead ValueWrapper
  lib/rxdart.dart
  lib/src/subjects/behavior_subject.dart
  lib/src/subjects/replay_subject.dart
  lib/src/transformers/backpressure/backpressure.dart
  lib/src/utils/collection_extensions.dart
  lib/src/utils/empty.dart
  lib/src/utils/notification.dart
  lib/src/utils/value_wrapper.dart
Labels: enhancement

#633 Improved CompositeSubscription
  lib/src/utils/composite_subscription.dart
  test/streams/composite_subscription_test.dart
Labels: enhancement

#635 feat(CompositeSubscription): `CompositeSubscription` implements `StreamSubscription`
  lib/src/streams/race.dart
  lib/src/utils/composite_subscription.dart
  lib/src/utils/subscription.dart
  test/streams/composite_subscription_test.dart
  test/streams/race_test.dart
Labels: enhancement

#639 refactor(CompositeSubscription): throws a StateError instead of a String
  lib/src/utils/composite_subscription.dart
Labels: enhancement
